### ISSUE TITLE
Evaluation Results and the version of evaluation openai  api

### ISSUE THREAD

**Issue by cathyxl** [imagegridworth/IG-VLM#2]
Hello~thanks for the interesting work. I have two questions about  the reproduction.

a. Could you release the results of the evaluated benchmarks?

b. What is the  openai model you used for the evaluations? It seems the gpt-3.5-turbo was changed from gpt-3.5-turbo-0613  to gpt-3.5-turbo-0125 recently. Just want to which model did you use?

**Comment by imagegridworth** [comment]
Hello Thank you for your interest.

Firstly, I can send you the Result file via email as it's too large to share here. Please request it via email, and I'll send it over.
I used the gpt-3.5-turbo model directly from the GPT API. During experimentation, version 0613 was also utilized, and the final test results were confirmed to be allocated under gpt-3.5-turbo-0125 according to the chatgpt policy.

Thank you.

**Comment by cathyxl** [comment]
Hi I've sent a email to imagegrid.video@gmail.com  and cced wonkyunkim.sj@snu.ac.kr yesterday.  As for the openai model, does that mean you use gpt-3.5-turbo-0125 for all the reported results in the paper, including open ended question answer  and text generation?
