### ISSUE TITLE
The inference time 

### ISSUE THREAD

**Issue by Lexarymade** [imagegridworth/IG-VLM#5]
Really appreciate the authors for open-sourcing this great project, but there is a little question for me about the time consume for the intentqa and nextqa dataset (which is what I'm work on)
The local inference time for me on these datasets are about 3hours and 6hours respectively, which I think is a little bit long. So I’m just wondering what's your time for the evaluation? And is there any tricks here to speed up the whole process?
I’m looking forward to your reply 😃

**Comment by imagegridworth** [comment]
Thank you for your interest. 

The inference time varies significantly depending on the GPU machine. In our experimentation with NExT-QA, it took 4 hours and 40 minutes on an RTX A6004, while on an L4, it took 10 hours.
Although GPU machine specifications have the most significant impact, to reduce time, pre-generate image grids and conduct inference could further decrease the time. Alternatively, when loading the llava model, passing 'use_flash_attn=True' to 'load_pretrained_model()' enables faster inference. However, this may affect reproducibility.

Thank you
Regards
